lista_acuerdos_default = [
    {"cant": 1, "texto": "perfil del proyecto"}, {"cant": 1, "texto": "título del proyecto"},
    {"cant": 1, "texto": "objetivo general"}, {"cant": 1, "texto": "sector económico"},
    {"cant": 1, "texto": "giro empresarial"}, {"cant": 1, "texto": "reporte de contribución al PIB"},
    {"cant": 1, "texto": "perfil del cliente"}, {"cant": 1, "texto": "análisis de mercado TI"},
    {"cant": 1, "texto": "estudio de factibilidad"}, {"cant": 1, "texto": "tabla de proyecciones financieras"},
    {"cant": 1, "texto": "tabla del análisis comparativo de la competencia"}, {"cant": 1, "texto": "tabla del plan operativo"},
    {"cant": 1, "texto": "tabla del plan general de trabajo"}, {"cant": 3, "texto": "diagramas de entrada, proceso y salida"},
    {"cant": 3, "texto": "listas de los recursos de entrada, proceso y salida"}, {"cant": 4, "texto": "tablas de los recursos enlistados de entrada, proceso y salida"},
    {"cant": 1, "texto": "diagrama CPM"}, {"cant": 1, "texto": "acta de constitución firmada"},
    {"cant": 1, "texto": "matriz de interesados"}, {"cant": 1, "texto": "documento de alcance del software"},
    {"cant": 1, "texto": "diagrama EDT/WBS"}, {"cant": 1, "texto": "plan de dirección integral"},
    {"cant": 1, "texto": "set de plantillas para usuarios"}, {"cant": 1, "texto": "software único de pruebas (Testify)"},
    {"cant": 1, "texto": "módulo de IA para conclusiones"}, {"cant": 5, "texto": "reportes de avance metodológico"},
    {"cant": 1, "texto": "proyecto de inversión técnica"}, {"cant": 1, "texto": "prototipo funcional validado"},
    {"cant": 1, "texto": "plano operativo técnico"}, {"cant": 1, "texto": "servidor PostgreSQl configurado"},
    {"cant": 1, "texto": "interfaz de usuario programada"}, {"cant": 3, "texto": "módulos de seguridad configurados"},
    {"cant": 1, "texto": "diseño estructural completo"}, {"cant": 1, "texto": "manual de estándares de proceso"},
    {"cant": 1, "texto": "reporte de integridad de datos"}, {"cant": 1, "texto": "set de módulos desarrollados"},
    {"cant": 1, "texto": "reporte de validación de IA"}, {"cant": 5, "texto": "protocolos de mantenimiento"},
    {"cant": 1, "texto": "documento de errores (QA)"}, {"cant": 15, "texto": "reportes de pruebas unitarias"},
    {"cant": 11, "texto": "reportes de actualización"}, {"cant": 2, "texto": "convenios de asociación"},
    {"cant": 1, "texto": "presupuesto de innovación"}, {"cant": 1, "texto": "reporte de retorno de inversión"},
    {"cant": 1, "texto": "plan de adquisición de activos"}, {"cant": 1, "texto": "tarifario oficial de Testify"},
    {"cant": 4, "texto": "reportes presupuestales"}, {"cant": 1, "texto": "bitácora de administración"},
    {"cant": 11, "texto": "comprobantes de dispersión"}, {"cant": 11, "texto": "balances generales"},
    {"cant": 5, "texto": "contratos laborales firmados"}, {"cant": 1, "texto": "programa de capacitación integral"},
    {"cant": 1, "texto": "sistema de evaluación"}, {"cant": 5, "texto": "perfiles de puesto validados"},
    {"cant": 3, "texto": "módulos formativos diseñados"}, {"cant": 1, "texto": "manual de indicadores (KPIs)"},
    {"cant": 15, "texto": "reportes de entrevista"}, {"cant": 5, "texto": "bitácoras de inducción"},
    {"cant": 11, "texto": "reportes de evaluación mensual"}, {"cant": 6, "texto": "contratos de licencia firmados"},
    {"cant": 1, "texto": "reporte de posicionamiento"}, {"cant": 1, "texto": "plan de post venta detallado"},
    {"cant": 1, "texto": "cartera de 20 prospectos"}, {"cant": 1, "texto": "presentación ejecutiva (Pitch Deck)"},
    {"cant": 1, "texto": "manual de niveles de servicio"}, {"cant": 6, "texto": "expedientes de contrato cerrados"},
    {"cant": 10, "texto": "bitácoras de demostración"}, {"cant": 6, "texto": "reportes de satisfacción"},
    {"cant": 1, "texto": "tabla de checklist de verificación"}, {"cant": 1, "texto": "bitácora de control de cambios"},
    {"cant": 1, "texto": "reporte de seguimiento de hitos"}, {"cant": 1, "texto": "matriz de resultados finales"},
    {"cant": 1, "texto": "reporte de costos reales vs planeados"}, {"cant": 1, "texto": "análisis de valor ganado"},
    {"cant": 1, "texto": "acta de cierre del proyecto firmada"}
]