lista_hitos_default = [
    "Tema", "Título", "Objetivo", "Sector", "Giro", "PIB", "Cliente", "Mercado", "Aceptación del mercado",
    "Proyección de ventas", "Benchmarking", "Plan operativo", "Plan general de trabajo", "Plan de comercialización",
    "Cronograma de Actividades", "Red CPM", "Acta de constitución del proyecto", "Gestión de interesados",
    "Gestión del alcance", "EDT", "Gestión de dirección del proyecto", "Plantillas de requisitos",
    "Diseñar y desarrollar un software único", "Gestionar una innovación de IA", "Gestionar una innovación técnica de IA",
    "Gestionar el proyecto integral", "Realizar el proyecto de inversión técnica", "Desarrollar el prototipo funcional",
    "Realizar el plan operativo técnico", "Instalar la infraestructura de red", "Programar la interfaz de usuario",
    "Configurar los módulos de seguridad", "Diseñar la estructura funcional y técnica del software",
    "Gestionar la estandarización de procesos de reportes", "Supervisar la integridad de la base de datos y flujo",
    "Desarrollar los módulos de software", "Validar los algoritmos de IA para el mapeo de datos",
    "Estructurar los protocolos de mantenimiento y actualización", "Documentar las pruebas de errores y rendimiento",
    "Ejecutar las pruebas unitarias de los módulos", "Realizar las actualizaciones de seguridad en la BD",
    "Obtener afiliaciones con socios capitalistas", "Gestionar el presupuesto de innovación",
    "Realizar la proyección de recuperación financiera", "Determinar el capital para activos y equipo",
    "Definir el tarifario de licencias anuales", "Obtener el presupuesto trimestral de nómina",
    "Administrar el fondo de infraestructura física", "Ejecutar el pago mensual de salarios",
    "Realizar el balance de caja mensual", "Contratar personal especializado", "Capacitar al personal en metodologías y BD",
    "Establecer el sistema de evaluación del desempeño", "Definir los perfiles de puesto y competencias técnicas",
    "Diseñar los talleres formativos de la arquitectura", "Estructurar los KPIs de productividad del equipo",
    "Realizar las entrevistas y pruebas técnicas", "Ejecutar la inducción técnica al nuevo personal",
    "Aplicar las encuestas de desempeño mensuales", "Vender el licenciamiento anual a las empresas de TI",
    "Posicionar a Testify en el mercado de la CDMX", "Diseñar el plan de post venta y mantenimiento",
    "Realizar la prospección de clientes", "Desarrollar el pitch deck comercial de Testify",
    "Definir los niveles de soporte y acuerdos", "Cerrar los contratos legales con los clientes",
    "Ejecutar las demos técnicas para jefes de área", "Gestionar encuestas de satisfacción y eficiencia",
    "Checklist de verificación", "Control de cambios", "Control de seguimiento", "Plantilla de resultados",
    "Plantilla de costos", "Plantilla de valor ganado", "Plantilla de acta de cierre"
]